package com.example.Social_Media_Platform.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.Social_Media_Platform.Util.DateConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "FriendRequests")
public class FriendRequest {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String senderId;

    @DynamoDBAttribute
    private String receiverId;

    @DynamoDBAttribute
    private String status = "Pending";

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "receiver-status-index")
    private String receiverIdStatus = receiverId + "#" + status;

    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdAt;

    @DynamoDBIgnore
    public String getReceiverIdStatus() {
        return receiverId + "#" + status;
    }
}
