package com.example.Social_Media_Platform.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.Social_Media_Platform.Util.DateConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Posts")
public class Post {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId-createdAt-index", attributeName = "userId")
    private String userId;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    private String imageUrl;

    @DynamoDBAttribute
    private int likeCount = 0;

    @DynamoDBAttribute
    private int commentCount = 0;

    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "userId-createdAt-index", attributeName = "createdAt")
    private Date createdAt;

    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedAt;
}