package com.example.Social_Media_Platform.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.Social_Media_Platform.Util.DateConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Users")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index")
    private String email;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "username-index")
    private String username;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String avatarUrl;

    @DynamoDBAttribute
    private String bio;

    @DynamoDBAttribute
    private String status = "Active";

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedAt;
}